### ISSUE TITLE
bazel build error

### ISSUE THREAD

**Issue by Arnold1** [google/yggdrasil-decision-forests#23]
hi,

I try to build Yggdrasil with the latest main branch and run into an error - any idea how to get it build?
```
root@641936fb6db1:~/yggdrasil-decision-forests# bazel build //yggdrasil_decision_forests/cli:all --config=linux_cpp17 --config=linux_avx2                              
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=168
INFO: Reading rc options for 'build' from /home/developer/yggdrasil-decision-forests/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/developer/yggdrasil-decision-forests/.bazelrc:
  'build' options: -c opt --spawn_strategy=standalone --announce_rc --noincompatible_strict_action_env --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --define=grpc_no_ares=true --color=yes
INFO: Found applicable config definition build:linux_cpp17 in file /home/developer/yggdrasil-decision-forests/.bazelrc: --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=linux
INFO: Found applicable config definition build:linux in file /home/developer/yggdrasil-decision-forests/.bazelrc: --copt=-fdiagnostics-color=always --copt=-w --host_copt=-w
INFO: Found applicable config definition build:linux_avx2 in file /home/developer/yggdrasil-decision-forests/.bazelrc: --copt=-mavx2
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/093ed77f7d50f75b376f40a71ea86e08cedb8b80.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository llvm-raw instantiated at:
  /home/developer/yggdrasil-decision-forests/WORKSPACE:40:4: in <toplevel>
  /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/org_tensorflow/tensorflow/workspace3.bzl:42:9: in workspace
  /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/org_tensorflow/third_party/llvm/workspace.bzl:10:20: in repo
  /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/org_tensorflow/third_party/repo.bzl:128:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/org_tensorflow/third_party/repo.bzl:81:35: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class java.io.IOException Read timed out
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
        File "/home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/org_tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/llvm-raw/temp10191920695629813942/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
ERROR: /home/developer/yggdrasil-decision-forests/WORKSPACE:40:4: fetching _tf_http_archive rule //external:llvm-raw: Traceback (most recent call last):
        File "/home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/org_tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/llvm-raw/temp10191920695629813942/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
ERROR: no such package '@llvm-raw//utils/bazel': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/developer/.cache/bazel/_bazel_root/24e8bb26857d60bf6cc54958294ec961/external/llvm-raw/temp10191920695629813942/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
INFO: Elapsed time: 182.660s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

it looks like its related to: https://github.com/tensorflow/tensorflow/issues/56422

**Comment by rstz** [comment]
Hi, this is very likely a tensorflow issue, see tensorflow/tensorflow#56540 -  we hope that this gets resolved soon

**Comment by rstz** [comment]
This issue has been resolved on the Tensorflow / LLVM / Github side and compilation works again
